version: "3.9"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html:ro
    depends_on:
      - php
      - mysql
    networks:
      - monelo_net
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: mysql
      DB_NAME: monelo
      DB_USER: monelo
      DB_PASS: monelo
      BASE_URL: "http://kopimonelo.com"
      GOOGLE_CLIENT_ID: ""
      GOOGLE_CLIENT_SECRET: ""
    networks:
      - monelo_net
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: monelo
      MYSQL_USER: monelo
      MYSQL_PASSWORD: monelo
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - monelo_net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: monelo
      PMA_PASSWORD: monelo
    networks:
      - monelo_net
    depends_on:
      - mysql
networks:
  monelo_net:

